### ISSUE TITLE
Docker compose DB_HOST env value

### ISSUE THREAD

**Issue by egotto** [dyrkin/luxmed-bot#58]
In the run.sh script, the DB_HOST value from environment variables is not used. This means if you use a different name for the service in the docker-compose.yaml file, the bot won't start.

```yaml
services:
  luxmedbookingservice:
    depends_on:
    - postgreSql
    image: eugenezadyra/luxmed-bot:latest
    environment:
      DB_HOST: postgreSQL
      DB_PORT: 5432
      SECURITY_SECRET: ${SECURITY_SECRET}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    volumes:
    - lbs:/lbs
    restart: unless-stopped
    network_mode: bridge

  postgreSql:
    image: postgres:10.6
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'lbs'
      TZ: 'Europe/Warsaw'
    restart: unless-stopped
    network_mode: bridge

volumes:
  postgres:
    name: postgres
  lbs:
    name: lbs
```

```
nc: getaddrinfo for host "database" port 5432: Name or service not known
nc: getaddrinfo for host "database" port 5432: Name or service not known
nc: getaddrinfo for host "database" port 5432: Name or service not known
```
