### ISSUE TITLE
Usage of ram

### ISSUE THREAD

**Issue by Ukey89** [dyrkin/luxmed-bot#93]
Is there any way to limit the amount of RAM USAGE in docker ? Currently, the bot uses ~450MB and my vps is limited to 256MB.

**Comment by y0rune** [comment]
Yeah yeah! When you would like to limit here is a code in docker-compose.yml
```
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
```
